version: '3'
services: 
  app:
    build: .
    ##command: bash -c "rake neo4j:generate_schema_migration[constraint,UserNode,uuid] && rake neo4j:generate_schema_migration[constraint,ClassNode,uuid] && rake neo4j:generate_schema_migration[constraint,DateNode,uuid]&& rake neo4j:migrate"
    depends_on: 
        - neo4j
    links:            ## connects neo4j to app container
        - neo4j
    restart: always
    volumes:
        - ./db/neo4j/migrate/:/app/db/neo4j/
    environment: 
        - TZ=Australia/Melbourne
        - CRON=0 30 6 * * MON-SAT
        - BOT_TOKEN=NDU3NDQ2MTkyNzU0OTgyOTMy.WyS79w.0JzH1DBK-MVzbCRXQ71f0MmEo_Q

  neo4j:
    image: neo4j:3.5.28
    hostname: neo4j
    container_name: neo4j
    restart: unless-stopped
    ports:
        - 7474:7474
        - 7687:7687
    volumes:
        - ./db/neo4j/conf:/conf
        - ./db/neo4j/data:/data
        - ./db/neo4j/import:/import
        - ./db/neo4j/logs:/logs
        - ./db/neo4j/plugins:/plugins
    environment: 
        - NEO4J_AUTH=none